name: Update

on:
  schedule:
    # run every friday
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  pacakges:
    name: Update packages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update packages
        run: |
          nix run .#update-packages -- --skip-prompt --commit

      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          title: "chore: update packages"
          sign-commits: true

      - name: Enable Automerge
        if: ${{ steps.pull-request.outputs.pull-request-number }}
        run: |
          gh pr merge --merge --auto "$PR_ID"
        env:
          PR_ID: ${{ steps.pull-request.outputs.pull-request-number }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
