name: Update

on:
  schedule:
    # run every friday
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  pacakges:
    name: Update packages
    runs-on: ubuntu-latest
    environment: update

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Setup git user
        # run: |
        #   git config --global user.name 'github-actions[bot]'
        #   git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - name: Update packages
        run: |
          nix run .#update-packages -- --skip-prompt --commit

      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          delete-branch: true
          title: "chore: update packages"
          sign-commits: true

      # - name: Enable Automerge
      #   if: ${{ steps.pull-request.outputs.pull-request-number }}
      #   run: |
      #     gh pr merge --merge --auto "$PR_ID"
      #   env:
      #     PR_ID: ${{ steps.pull-request.outputs.pull-request-number }}
      #     GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
